CREATE DATABASE PROJETO_INTEGRADO;

USE PROJETO_INTEGRADO;


CREATE TABLE CADASTRO_DESCARTE (
  
  ID_PESQUISA INT PRIMARY KEY,
  PESQUISA VARCHAR(200)
  NOME_RUA VARCHAR(200),
  NUMERO INT,
  BAIRRO VARCHAR(200),
  TELEFONE VARCHAR(200),
  EMAIL VARCHAR(200)
  

);

